easy_admin:
   # site_name: "SuperShop."
   site_name: '<img src="http://symfony.com/logos/symfony_white_01.png" />'
   entities:
       # List the entity class name you want to manage
       - App\Entity\Product
       - App\Entity\Category
       # - App\Entity\User
       - App\Entity\Cart
       - App\Entity\Catalog
    